exclude_paths:
- "admin"
- "application"
- "files"
- "install"
- "plugins/Coins"
- "plugins/CsvImportPlus"
- "plugins/DublinCoreExtended"
- "plugins/ExhibitBuilder"
- "plugins/SimplePage"
- "themes/ani-yun-wiya"
- "themes/berlin"
- "themes/default"
- "themes/omeka-starter-theme"
- "themes/Scribe"
- "themes/seasons"